### PR TITLE
New Replay Test for Removing Dirt

### PR DESCRIPTION
**Pull request by MKDEVELOPEMENT**
Replay Test removing two blocks of Dirt, one by 'hand' and one with shovel.

### CODE REVIEW

**Review by iaronaraujo — CHANGES_REQUESTED** [review]
Thank you for the PR, MK! The code of the test seems solid, but there are some problems with the recording. Since this is a PR to the "newSerialization" branch, the recording should have been created using terasology's engine's "newSerialization" branch too, since the JSONs are created on a different way there. Besides that, even when I try to test the recording using the engine's "develop" branch, the recording seems to get stuck at the beginning, so the test never executes.
To fix this problem, you can recreate the recording using the engine's "newSerialization" branch and then change the values of "dirtLocation1" and "dirtLocation2" since they will probably change with the new recording!

**Comment by iaronaraujo** [comment]
@llvieira tested your PR using the engine's "develop" branch and it worked there! This problem might have been something wrong with my computer. Therefore, the only problem of your commit is that the recording was made using the engine's "develop" branch instead of "newSerialization"!

**Comment by llvieira** [comment]
Good work, MK! As @iaronaraujo said, you have to create the test using `newSerialization` branch in both Terasology and TestReplayModule. You'll notice that `events.json` have a different structure when using Terasology `newSeralization` branch.  

@iaronaraujo had a problem running tests on his machine, but here they are OK. So please, fix this problem and submit your task for review again, after that your task will be good to go.

**Comment by MKDEVELOPEMENT** [comment]
Hey, I have made a new replay test with the recording performed with the newSerialization branch, and removed the old replay files that were with the master branch

**Review by iaronaraujo — CHANGES_REQUESTED** [review]
Thank you for the changes! I tested this changes and I noticed that the recording is still in the old serialization format. This may have happened because your version of the "newSerialization" branch is not updated. To update it, you will probably need to make a "git pull" or rebase the branch from the upstream. If you have any questions about how to do that, feel free to ask on discord!
You will know the Recording is on the right format when the "event1.json" file looks like [this](https://github.com/Terasology/TestReplayModule/blob/newSerialization/assets/recordings/Woodcut/events1.json)

**Comment by MKDEVELOPEMENT** [comment]
Hey, sorry for all the complications on my side, git was a bit of a challenge, but I am sure that it is all fixed now, everything works as expected - no issues with replaying/tests. Looking forward to the feedback!

**Review by iaronaraujo — APPROVED** [review]

**Comment by iaronaraujo** [comment]
It's working perfectly now! Thank you very much for your contribution!

**Comment by MKDEVELOPEMENT** [comment]
Thanks for all the help along the way! Glad to have contributed

**Pull request merged**
